services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  postgres_volume:
